# Generated by Django 2.1 on 2020-03-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCode',
            fields=[
                ('pcode', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'project_code',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('pcode', models.CharField(max_length=4)),
                ('user_id', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('content', models.CharField(blank=True, max_length=1000, null=True)),
                ('is_complete', models.IntegerField(blank=True, null=True)),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'todo_list',
                'managed': False,
            },
        ),
    ]
